name: Publish

on:
  push:
    tags:
      - v*

concurrency:
  group: publish-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --warning-mode all --build-cache

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: "build/libs/*.jar"
          generate_release_notes: true
          fail_on_unmatched_files: true

      - name: Publish to CurseForge
        env:
          CURSEFORGE_API_KEY: "${{ secrets.CURSEFORGE_API_KEY }}"
        run: ./gradlew curseforge --warning-mode all --build-cache

      - name: Publish to Modrinth
        env:
          MODRINTH_API_KEY: "${{ secrets.MODRINTH_API_KEY }}"
        run: ./gradlew modrinth --warning-mode all --build-cache
